### DISCUSSION TITLE
Why does the example trigger on pull requests, but not push on pull requests?

### DISCUSSION THREAD

**Discussion by rothnic** [docker/metadata-action#344] [Q&A]
I feel like I generally understand the concept of this workflow, but I'm just not following logic behind the [Basic Example](https://github.com/docker/metadata-action#basic). 

The example starts with this:

```
pull_request:
    branches:
      - 'master'
```
I interpret this as triggering this workflow any time a pull request is opened against the master branch. It seems like this would be useful for evaluating a pull request because the image would be ready to test without having to manually checkout and build it.

However, I then see this part:

```
name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

In particular, the `push: ${{ github.event_name != 'pull_request' }}` is confusing without any specific comments on why that might be used. In other words, why would you not want to push an image for a pr if you have already gone through the trouble of building the image? I suppose that we might want to just see that the image is built, but why would we not want to just go ahead and have the image anyways?

It just seems like this very specific approach is being used in multiple examples([1](https://docs.docker.com/build/ci/github-actions/manage-tags-labels/), [2](https://github.com/docker/metadata-action#basic), [3](https://github.com/docker/metadata-action#semver)) without some explanation of what the underlying goal is. This just adds to the uncertainty of reading and understanding the documentation.
