### DISCUSSION TITLE
How can I get only one image tag in the output?

### DISCUSSION THREAD

**Discussion by mendhak** [docker/metadata-action#376] [Q&A] [answered]
I've got a Github Action that's set to run on push of a git tag. 
The `docker/metadata-action` produces two image tags in its output. 
One for the git tag itself, eg "v1.2.3" and one for "latest". 

```
    - name: Get Metadata for Docker Image
      id: metadata
      uses: docker/metadata-action@v5
      with:
        images: ${{ steps.login-ecr.outputs.registry }}/myimage
        tags: |
          type=ref,event=tag,priority=1000
```

I'm only interested in getting the "v1.2.3" output. Is there an easy way to do that? 

The reason is, I'm passing it to the `aws-actions/amazon-ecs-deploy-task-definition` action, which takes an image: input. When I try to give it 

```
image: ${{ steps.metadata.output.tags }}
```

It fails as it's expecting one image tag, not two.  

Thanks

**Comment by crazy-max** [comment, marked as answer]
You can set `latest=false` in `flavor` input: https://github.com/docker/metadata-action#flavor-input

More info about latest handling: https://github.com/docker/metadata-action#latest-tag

**Reply by mendhak** [reply]
That was it, thanks!

**Reply by mendhak** [reply]
```
- name: Get Metadata for Docker Image
      id: metadata
      uses: docker/metadata-action@v5
      with:
        images: ${{ steps.login-ecr.outputs.registry }}/myimage
        tags: |
          type=ref,event=tag,priority=1000
        flavor: |
          latest=false
```
