### DISCUSSION TITLE
is there a better way to get the fisrt tag?

### DISCUSSION THREAD

**Discussion by zhangguanzhang** [docker/metadata-action#397] [Q&A] [answered]
```
JSON output
  {
    "tags": [
      "***/process-exporter:v0.7.11",
      "***/process-exporter:latest"
    ],
```

workflow:
```
      - name: generate docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            xxx/process-exporter
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}}

      - name: Extract first Docker image tag
        id: first_tag
        run: echo "tag=$(echo '${{ steps.meta.outputs.tags }}' | awk '{print $1;exit}')" >> $GITHUB_OUTPUT
```

**Comment by crazy-max** [comment, marked as answer]
You can use `steps.meta.outputs.version`

**Reply by zhangguanzhang** [reply]
thanks

**Comment by zhangguanzhang** [comment]
first full name:
```
${{ fromJSON(steps.meta.outputs.json).tags[0] }}
```
there is a demo:
```
      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
```
