### DISCUSSION TITLE
How To Assign Tags To Multiple Targets From Single Bake Call?

### DISCUSSION THREAD

**Discussion by jvanderen1** [docker/metadata-action#417] [Q&A]
I am wondering how to assign tags to multiple images generated from a single Docker bake call with multiple targets?

## Setup

I have a multi-stage `Dockerfile` file constructed like so:

```dockerfile
FROM alpine:3.14 AS base
...

FROM base AS test
...

FROM base AS final
...
```

I have a `docker-compose.yml` file constructed like so:

```yml
name: "app"

services:
  final:
    build:
      context: .
      target: final

  test:
    build:
      context: .
      target: test
```

Finally, I am trying to construct the metadata properly for each image built as defined in my `docker-compose.yml` using Github Actions:

```yml
name: Test

on:
  pull_request:

jobs:
  build_and_push:
    ...

    steps:
      ...

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # TODO: I am wondering how to map the metadata 
          # generated from this action to the correct image from bake-action?
          images: |
            ${{ env.REGISTRY }}/app-test   # Should line up with `test` service in `docker-compose.yml`
            ${{ env.REGISTRY }}/app-final  # Should line up with `final` service in `docker-compose.yml`

      - name: Build and Push
        uses: docker/bake-action@v4
        with:
          push: true
          files: |
            ./docker-compose.yml
```

In the end, I would like to generate the following repositories + tags (on pull requests):

| REPOSITORY  | TAG |
| ------------- | ------------- |
| `${{ env.REGISTRY }}/app-final`  | `pr-1`  |
| `${{ env.REGISTRY }}/app-test`  | `pr-1`  |

## Related Info

This question feels similar to https://github.com/docker/metadata-action/issues/398, but there has not been any activity on it.
