### DISCUSSION TITLE
[Bake] How to define the workdir when `docker-bake.hcl` is under a subdirectory

### DISCUSSION THREAD

**Discussion by shink** [docker/metadata-action#433] [General]
Hi folks!

I'm using `metadata-action`. I have an question: how to define the workdir if `docker-bake.hcl` is not under the root repo?

Here is my structure:

```
root-repo
    ├── docker
        ├── docker-bake.hcl
```

```yaml
- name: Extract metadata for Docker
  id: metadata
  uses: docker/metadata-action@v5
  with:
    bake-target: "docker-metadata-action"
```
