### DISCUSSION TITLE
Is it possible to update the pr-# tag on pushes to the pull request?

### DISCUSSION THREAD

**Discussion by briceburg** [docker/metadata-action#452] [Q&A]
It seems that the `pr-#` tag is created _once_ when the pull request opens. 

I'd like subsequent pushes to the PR branch to re-tag the image so that the `image:pr-123` image always reflects the latest built image from PR-123. Is this possible?

My current implementation is:

```yaml
 - name: Determine Image Metadata (tags, labels)
    id: meta
    uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
    with:
      images: ${{ inputs.registry }}/${{ inputs.image }}
      tags: |
        type=schedule,priority=10
        type=ref,event=tag,priority=9
        type=sha,format=long,prefix=,priority=8
        type=ref,event=pr,priority=5
        type=ref,event=branch,priority=5
 ```
 
 which seems to only produce the sha and branch tags when I make pushes to the branch which has an open PR, e.g.
 
 ```
ghcr.io/foo/bar:208176a7386310c60ce19fb1adb1c4eaf5cb37f2
ghcr.io/foo/bar:my-branch
```

where I would expect the following if `my-branch` has an open PR (#123);

```
ghcr.io/foo/bar:208176a7386310c60ce19fb1adb1c4eaf5cb37f2
ghcr.io/foo/bar:pr-123
ghcr.io/foo/bar:my-branch
```
