### ISSUE TITLE
Tag images from PR with branch?

### ISSUE THREAD

**Issue by mgoodness** [docker/metadata-action#102]
#### Expected behaviour

When pushing to a PR branch, I expect to have a `devops-comedy:<branch>` and `devops-comedy:pr-<number>` tag generated - among others.

#### Actual behaviour

The `devops-comedy:<branch>` tag is not generated, and the two SHA tags that should be prefixed with the branch name are not.

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
name: devops-comedy

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate container metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: <my_repo>/devops-comedy
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=sha,prefix={{branch}}-
            type=sha,format=long
            type=sha,format=long,prefix={{branch}}-

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to MLB Artifactory
        uses: docker/login-action@v1
        with:
          registry: <mlb_registry>
          username: ${{ secrets.MLB_ARTIFACTORY_USERNAME }}
          password: ${{ secrets.MLB_ARTIFACTORY_PASSWORD }}

      - name: Build & push container image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=<my_repo>/devops-comedy:latest
          cache-to: type=inline
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Output container image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

```

### Logs

[logs_7.zip](https://github.com/docker/metadata-action/files/6634293/logs_7.zip)

**Comment by crazy-max** [comment]
@mgoodness 

> The `devops-comedy:<branch>` tag is not generated,

`type=ref,event=branch` is only generated on branch event (aka `refs/heads/<branch>`). Same goes with `type=ref,event=pr` on pr/pr_target event (`refs/pull/merge/<pr_num>`) and `type=ref,event=tag` on tag event (`refs/tags/<tag>`).

> and the two SHA tags that should be prefixed with the branch name are not.

About the [global expression `{{branch}}`](https://github.com/docker/metadata-action#global-expressions) empty on pr event, it's pretty much the same behavior as above but we could set `{{branch}}` with base branch value.

**Comment by mgoodness** [comment]
> type=ref,event=branch is only generated on branch event (aka refs/heads/<branch>).

I don't understand - AFAIK GitHub doesn't have a "branch" event.

**Comment by crazy-max** [comment]
@mgoodness `push branch` event:

```yaml
on:
  push:
    branches:
      - master
```
