### ISSUE TITLE
Support environment variables for image name

### ISSUE THREAD

**Issue by ksurl** [docker/metadata-action#105]
I tried using the builtin variable ${github_repository/docker-/} (stripping prefix from name via bash variable manipulation) as the value for images. The build failed since it did not evaluate it (also tried with quotes).

My current workaround is to have a step before it to set it as a string output and then use that as the value e.g. `${{ steps.image_names.output.images }}`

Comma separated list for pushing to multiple registries (docker hub and github container registry).

Would it be possible to add support for directly evaluating the variable? Or is it not good practice?

I reuse the same build workflow in my repos so I don't have to hardcode the names in each one.

**Comment by Cyb3r-Jak3** [comment]
You should be able to do something like

```yaml
      -
        name: Docker meta
        id: docker_meta
        uses: docker/docker-meta@v3
        with:
          images: ${{ env.REPOSITORY }},ghcr.io/${{ env.REPOSITORY }}
```

Do you have an example workflow you are using?

**Comment by ksurl** [comment]
I can't use it directly since my naming convention has docker- as a prefix for the application. if I try to set an environment variable with the bash replacement, it fails since it's not defined in a bash shell. I guess I'm stuck for now with an extra step to set the output to be reused in the image field. 

```
- name: Prepare docker image name
  id: image_names
  run: |
  IMAGES="${GITHUB_REPOSITORY/docker-/},ghcr.io/${GITHUB_REPOSITORY/docker-/}"
  echo ::set-output name=images::${IMAGES}

- name: Docker meta
  id: meta
  uses: docker/metadata-action@v3
  with:
    images: ${{ steps.image_names.outputs.images }}
    tags: |
      type=ref,event=tag
```

**Comment by Cyb3r-Jak3** [comment]
Given the need to remove the prefix you will need to have the step before.

If you wanted to do it with GitHub environment then you could try something like

```yaml
- name: Prepare docker image name
  run: echo "IMAGES="${GITHUB_REPOSITORY/docker-/},ghcr.io/${GITHUB_REPOSITORY/docker-/}" >> $GITHUB_ENV


- name: Docker meta
  id: meta
  uses: docker/metadata-action@v3
  with:
    images: ${{ env.IMAGES }}
    tags: |
      type=ref,event=tag
```
