### ISSUE TITLE
Using ref only for tag doesn't seem to work

### ISSUE THREAD

**Issue by donaldpiret** [docker/metadata-action#110]
#### Steps to reproduce this issue

1. Use the image-meta action with the following tags config:

            type=edge,branch=master
            type=ref,event=branch,enable=false
            type=ref,event=tag
            type=sha,format=long,prefix=sha-

#### Expected behaviour

when building a branch on push (eg. cicd-github-actions)

I should get the sha- tag
I should not get the cicd-github-actions tag (it's a branch, I don't want the ref for that)

#### Actual behaviour

Getting both the sha and branch tags

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
      - name: Set image name
        id: image-name
        run: |
          echo "IMAGE_NAME=${ECR_ACCOUNT_ID}.dkr.ecr.ap-southeast-1.amazonaws.com/${ECR_IMAGE_NAME}" >> $GITHUB_ENV
          echo ::set-output name=image_name::${ECR_ACCOUNT_ID}.dkr.ecr.ap-southeast-1.amazonaws.com/${ECR_IMAGE_NAME}
      - name: Docker meta
        uses: docker/metadata-action@v3
        id: image-meta
        with:
          images: |
            ${{ steps.image-name.outputs.image_name }}
          tags: |
            type=edge,branch=master
            type=ref,event=branch,enable=false
            type=ref,event=tag
            type=sha,format=long,prefix=sha-
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs)
> and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.
