### ISSUE TITLE
Missing required key 'github-token'

### ISSUE THREAD

**Issue by hiepnh610** [docker/metadata-action#123]
I am using your actions to get metadata. I do not know why telling me a message `Missing required key 'github-token' `
How can I solved this issue?
 

```yml
name: Node.js CI

on:
  push:
    branches:
      - 'master'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: yarn install --frozen-lockfile
      - run: yarn test

  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with: # I get a lint error tell me Missing required key 'github-token'
          images: ${{ secrets.DOCKERHUB_REPOSITORY }}
          tags: type=semver,pattern={{version}}

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

```
