### ISSUE TITLE
Handle multiple prefixes with Bake

### ISSUE THREAD

**Issue by felipecrs** [docker/metadata-action#124]
Let's say I have a Dockerfile like so:

```dockerfile
FROM debian:latest AS debian

[...]


# debian is the default
FROM debian


FROM ubuntu:latest AS ubuntu

[...]


FROM alpine:latest AS alpine

[...]
```

And a `docker-bake.hcl` like so:

```hcl
group "default" {
  targets = ["debian"]
}

group "all" {
  targets = ["debian", "ubuntu", "alpine", "centos"]
}

target "base" {
  context = "."
}

target "debian" {
  inherits = ["base"]
  target = "debian"
}

target "ubuntu" {
  inherits = ["base"]
  target = "ubuntu"
}

target "alpine" {
  inherits = ["base"]
  target = "alpine"
}
```

How could I integrate the Metadata Action with the Bake Action so I would have tags generated with prefixes like:

```
my-image:latest # debian
my-image:debian
my-image:ubuntu
my-image:alpine
```

And of course, tagging with semver like `my-image:alpine-1.1.0`.

**Comment by crazy-max** [comment]
@felipecrs If I understand correctly you want to transpose the bake target name as a tag?

**Comment by felipecrs** [comment]
> If I understand correctly you want to transpose the bake target name as a tag?

@crazy-max this specific point is just a coincidence.

One solution would be to:

1. metadata-action to allow setting multiple targets
2. metadata-action to allow setting default configuration that would be applied for all the multiple targets

Then, metadata-action instead of outputting a single target, it would output multiple targets.

**Comment by fourbytes** [comment]
I'm trying to do something similar to this. I have a repo with multiple micro-services, each service is pushed to a registry (`ghcr.io/<owner>/<project>/<service>:<tag>`) and it doesn't seem possible to use this metadata data action to set the tags for each service at the moment.
I could do it with multiple steps however that would slow down the build as they'd have to run sequentially.

**Comment by sandhose** [comment]
I had this exact problem, and figured that the bake files are just JSON files that can be merged with `jq`. This is how I solved it, by running the action twice and merging the files:

https://github.com/matrix-org/matrix-authentication-service/blob/1df5cf42e32abaeedddc504afeb431d77154f78f/.github/workflows/check.yaml#L317-L345

 ```yaml

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: "${{ env.IMAGE }}"
          bake-target: docker-metadata-action
          tags: ...

      - name: Docker meta (debug variant)
        id: meta-debug
        uses: docker/metadata-action@v3
        with:
          images: "${{ env.IMAGE }}"
          bake-target: docker-metadata-action-debug
          tags: ...

      - name: Merge buildx bake files
        run: |
            jq -s '.[0] * .[1]' ${{ steps.meta.outputs.bake-file }} ${{ steps.meta-debug.outputs.bake-file }} > docker-bake.override.json
```
That way I have two different targets filled in my bake file: https://github.com/matrix-org/matrix-authentication-service/blob/1df5cf42e32abaeedddc504afeb431d77154f78f/docker-bake.hcl#L4-L6
