### ISSUE TITLE
Enable context support

### ISSUE THREAD

**Issue by llaumgui** [docker/metadata-action#126]
### Behaviour

Can't use _context_ like docker/build-push-action.

#### Steps to reproduce this issue

1. Put Dockerfile in a specific folder and not in the root.
2. Launch.
3. metadata-action fail.

#### Expected behaviour

Use a _context_ with `with` parametter.

#### Actual behaviour

_context_ isn't available with `with` parametter.

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
name: Docker Image CI

on:
  [push, pull_request]
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: llaumgui/php-fpm

jobs:

  ##############################################################################
  # Build job
  #
  build:
    runs-on: ubuntu-latest
    name: Build docker image

    strategy:
      fail-fast: false
      matrix:
        #php-version: [7.3, 7.4, "8.0"]
        php-version: ["8.0"]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v3

    # Build and push Docker image with Buildx (don't push on PR)
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ${{ matrix.php-version }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
```

### Logs

```
Error: images input required
```
