### ISSUE TITLE
Add option to choose between git or workflow context to generate metadata

### ISSUE THREAD

**Issue by lucacome** [docker/metadata-action#139]
### Behaviour

I have a workflow that checks out the latest tag and rebuilds the Docker image if the base image was updated. Context info contains info from master:
```
Context info
  eventName: schedule
  sha: 1c0577d958b4b4bed278593872a3c29f02981a0d
  ref: refs/heads/master
  workflow: Update Docker Images
  action: meta
  actor: lucacome
  runNumber: 134
  runId: 1335539062
```

#### Steps to reproduce this issue

1. Run the workflow on a schedule
2. Checkout a tag
3. The sha is not the correct one

#### Expected behavior

`org.opencontainers.image.revision` contains the sha from the tag that was checked out

#### Actual behaviour

`org.opencontainers.image.revision` contains the sha from the latest commit on `master`

### Configuration

* Repository URL (if public): https://github.com/nginxinc/kubernetes-ingress/blob/master/.github/workflows/update-docker-images.yml
* Build URL (if public): https://github.com/nginxinc/kubernetes-ingress/runs/3877415389?check_suite_focus=true#step:11:20

```yml
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: v${{ needs.variables.outputs.kic-tag }}

       ....
 
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            nginx/nginx-ingress
            ghcr.io/nginxinc/kubernetes-ingress
          flavor: |
            latest=true
            suffix=...not relevant...
          tags: |
            type=raw,value=${{ needs.variables.outputs.kic-tag }}
            type=raw,value=${{ steps.tag.outputs.short }}
          labels: ...not relevant...

```

### Logs
[logs_11965.zip](https://github.com/docker/metadata-action/files/7334344/logs_11965.zip)

**Comment by crazy-max** [comment]
@lucacome 

> there's always a checkout in the job

Not always. You can build a Docker image using a Git context so it does not require the checkout step.

> Maybe an input flag to enable getting the info from the current commit? Just throwing it out there 😄

Yeah I understand what you mean but the action heavily relies on on the current context via the hydrated Octokit client (aka [`@actions/github`](https://github.com/actions/toolkit/tree/main/packages/github)).

I will think about it, maybe something like:

```yaml
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          context: <workflow|git>
```
