### ISSUE TITLE
event=branch is triggered on push a tag

### ISSUE THREAD

**Issue by vterdunov** [docker/metadata-action#144]
#### Steps to reproduce this issue

1) docker/metadata-action@v3.6.0
```yaml
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - stable
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
```
```yaml
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3.6.0
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.SERVICE_NAME }}
          tags: |
            event=branch,type=raw,value={{branch}}-{{sha}}  # <---- triggered on push a tag
            event=branch,type=ref,suffix=-{{sha}}
            event=tag,type=semver,pattern={{version}}
```
2) `git tag 9.9.7; git push --tags`

#### Expected behaviour

I guess, the metadata `event=branch,type=raw,value={{branch}}-{{sha}}` should not be set.

#### Actual behaviour

Docker meta tags are:
```
service-name:9.9.7
service-name:-6c6ef40      # <---- branch is empty because event triggered by pushing a tag.
service-name:latest
```

Github Action context:
```
GITHUB_REF=refs/tags/9.9.7
...
GITHUB_EVENT_NAME=push
```
```
"ref": "refs/tags/9.9.7"
...
"ref_type": "tag",
...
"event_name": "push",
```
