### ISSUE TITLE
Default branch (master or main) gets pushed to master/main tag and not to the default name latest

### ISSUE THREAD

**Issue by guysoft** [docker/metadata-action#147]
### Behaviour

Default branch (master or main) gets pushed to master/main tag and not to the default docker name ``latest``.
I think this should rather be a feature, or there should be some doc on how to do this (perhaps there one I missed, would love it to be linked if possible).

#### Steps to reproduce this issue

1. Push the default branch

#### Expected behaviour

> Should also push to latest branch, or there should be a way to define which branch is set as the latest

#### Actual behaviour

Pushes to master/main

### Configuration

Example build:
https://github.com/guysoft/CustomPiOS/blob/devel/.github/workflows/docker-build.yml

```yaml
name: ci

on:
  push:
    branches:
      - "master"
      - "devel"
      - "docker-github-actions"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Docker meta tag
        id: docker_meta
        uses: docker/metadata-action@v3.5.0
        with:
          images: guysoft/custompios
          tag-sha: true
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: src
          file: src/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MY_GITHUB_TOKEN }}
```

**Comment by crazy-max** [comment]
@guysoft `tag-sha` input does not exist for the metadata action.

> Default branch (master or main) gets pushed to master/main tag and not to the default docker name `latest`.

Your workflow does not look really standard to me as latest tag should reflect the latest stable version and not an edge release. Anyway if you want the `latest` tag for the default branch but keep branch name as tag for the other branches, you have to use something like this:

```yaml
      -
        name: Docker meta tag
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: guysoft/custompios
          tags: |
            type=ref,event=branch,enable=${{ !endsWith(github.ref, github.event.repository.default_branch) }}
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
          flavor: |
            latest=false
```

Here we tell the metadata action to enable tag on branch for non default ones and create latest tag only for the default branch. We also have to disable the `latest` [flavor](https://github.com/docker/metadata-action#flavor-input) here otherwise [latest tag will be in auto mode](https://github.com/docker/metadata-action#latest-tag).
