### ISSUE TITLE
github-token set as required input

### ISSUE THREAD

**Issue by pirafrank** [docker/metadata-action#151]
#### Steps to reproduce this issue

1. add this as step to a github action
2. add inputs using the `with` tag as written in the doc
3. `github-token` input is expected. Documentation does not mention it in any example, nor how to valuate it.

#### Expected behaviour

Either user should be instructed about the need of `github-token` input, or this input should be optional and github.token should be read by default, as written in the action yaml specification (check your current code below).

#### Actual behaviour

Validator in VS Code gives an error saying: *"missing required key "github-token"*.

Your current implementation sets github-token as a required input field, (from https://github.com/docker/metadata-action/blob/master/action.yml):

```yaml
  github-token:
    description: 'GitHub Token as provided by secrets'
    default: ${{ github.token }}
    required: true
```
