### ISSUE TITLE
quotes in list inputs cause "Invalid Opening Quote"

### ISSUE THREAD

**Issue by actualben** [docker/metadata-action#152]
### Behaviour

When a list item value contains quotes, like the following label:

```yaml
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: example
          labels: |
            org.opencontainers.image.description=this is a "good" example
```

The error: `Error: Invalid Opening Quote: a quote is found inside a field at line 1` is produced. Previously this was touched on in #87 and as a result there was [a change to `build-push-action`'s input parsing](https://github.com/docker/build-push-action/pull/369). That didn't cover the case where the quote-containing value is an input to **this** action.

Does it make sense to add `relax: true,` to [the input parsing](https://github.com/docker/metadata-action/blob/5220b231121b5b69d5effbe0d0e4770a68500a44/src/context.ts#L51) in this action as well? If not, it probably makes sense to document the proper way to escape quotes somewhere in the metadata-action docs.

#### Steps to reproduce this issue

1. have a label or other list input item which contains quotation marks
2. run action

#### Expected behaviour

I'd expect there to be a documented way to have a label containing quotes.

#### Actual behaviour

> `Error: Invalid Opening Quote: a quote is found inside a field at line 1`

### Configuration

see yaml snippet in Behaviour section above
