### ISSUE TITLE
how to access generated tag type?

### ISSUE THREAD

**Issue by jeacott1** [docker/metadata-action#164]
currently, output tags are a list.
I'd like to be able to access the sha tag generated by metadata-action independently of the others for subsequent processing.

thoughts and hints on how I can achieve this?

thanks.

**Comment by crazy-max** [comment]
@jeacott1 You can use the [JSON output object](https://github.com/docker/metadata-action#json-output-object) that looks like this:

```json
{
  "tags": [
    "localhost:5000/name/app:nightly",
    "localhost:5000/name/app:master",
    "ghcr.io/name/app:nightly",
    "ghcr.io/name/app:master"
  ],
  "labels": {
    "org.opencontainers.image.title": "metadata-action",
    "org.opencontainers.image.description": "GitHub Action to extract metadata (tags, labels) from Git reference and GitHub events for Docker",
    "org.opencontainers.image.url": "https://github.com/docker/metadata-action",
    "org.opencontainers.image.source": "https://github.com/docker/metadata-action",
    "org.opencontainers.image.version": "nightly",
    "org.opencontainers.image.created": "2022-02-01T08:05:35.981Z",
    "org.opencontainers.image.revision": "2cad85de2462ab92a22ff973a347fb25c91d6082",
    "org.opencontainers.image.licenses": "Apache-2.0",
    "maintainer": "CrazyMax"
  }
}
```

So in your workflow your need to use `tags` in this object:

```yaml
      -
        run: |
          # iterate over ${{ fromJSON(steps.meta.outputs.json).tags }}
```

**Comment by jeacott1** [comment]
@crazy-max that doesnt actually answer the question at all.
in your example the tags are a list. how should I identify the sha tag specifically?
nowhere in tags or labels is the string provided as a sha-tag actually accessible as an identifiable field anywhere.

**Comment by crazy-max** [comment]
We only provide the [outputs provided in the README](https://github.com/docker/metadata-action#outputs). Like I said you can iterate over the list of tags from `tags` output or the JSON output object.

I don't see the point to add the sha tag as a specific output otherwise we would need to do that for all the other ones and that's not the purpose of this action. But if you still want the sha you can use the official [`github` context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) in your workflow to have this info: `${{ github.sha }}`.

**Comment by jeacott1** [comment]
@crazy-max re "We only provide the outputs provided in the README. "
hence this issue!
so lets think this through. in order for me to find the git sha tag, I need to first select the list of tags, then I need to grab the "org.opencontainers.image.revision" label and iterate and compare if the tag matches the first part of that label?
seriously could it be more painful! 
Since it is clear that there isnt a sensible option to access the git tag generated by this action, and its generated via a specific tag type=sha, don't you think it reasonable that I be able to discover the actual output of that directive? 
please consider this a feature request.

**Comment by crazy-max** [comment]
@jeacott1 What's your use case? Can you show your workflow?

**Comment by jeacott1** [comment]
@crazy-max
sure.
from a PR I'm generating images and pushing to a repository with a sha tag as generated by metadata-action.
a draft release is also created named for this PR and its contents are kept in sync with the conventional commit messages in the various commits in this PR.
When the PR is merged with main, a new sha and image is again generated and pushed to the repo so that internally tracking sha refs match the merge commit.
Now maybe this next part is folly? but I think the metadata-action should operate consistently from a published event?
After a human checks the release draft, cleans up any details, changes the release tag and name to something suitable and hits 
 the release button, at this point I want to use the output from metadata-action (specifically its generated sha tag name, and yes it will run again but I expect the sha tag to be consistent) so that I can add a new docker repo tag named for the release tag - replacing the existing sha-xxx tag (well, adding a new one and removing the old one, but both pointing to the same image) with no need to regenerate or push a new image. - all I need to do this is a reliable way to access the sha tag as generated by metadata-action.

**Comment by crazy-max** [comment]
@nlarusstone We can't, this is not supported by GitHub.

**Comment by G-man83** [comment]
> currently, output tags are a list. I'd like to be able to access the sha tag generated by metadata-action independently of the others for subsequent processing.
> 
> thoughts and hints on how I can achieve this?
> 
> thanks.

For anyone else who found this question and need an answer, I've done this using a step like:

``` yml
      # Output the sha image tag that was pushed to the registry.
      # The script uses ./jq to parse the JSON output from the docker/metadata-action@v4 action.
      # See https://jqlang.github.io/jq/ for more information.
      - name: Output SHA image tag
        id: output_sha_image_tag
        env:
          DOCKER_METADATA: ${{ steps.docker_meta.outputs.json}}
        run: |
          # pretty print the metadata
          echo $DOCKER_METADATA | jq '.'

          # get the image tag that contains 'sha-'
          image_tag=$(echo "$DOCKER_METADATA" | jq -r '.tags[] | select(. | test("sha-"))')
          echo $image_tag

          # get the sha from the image tag, for example: sha-1234567890abcdef1234567890abcdef12345678
          image_tag_sha=$(echo "$image_tag" | grep -o 'sha-[a-f0-9]\+')
          echo $image_tag_sha

          echo "image_tag_sha=$image_tag_sha" >> $GITHUB_OUTPUT
```

It uses the `json` output from the `docker/metadata-action@v4` action and parses the `tags` to get the `sha-*` tag. The value is then set as an output and can be used by subsequent steps or jobs.
