### ISSUE TITLE
Support for "release" type event?

### ISSUE THREAD

**Issue by HealthyPear** [docker/metadata-action#168]
It is not clear to me if there is support (or if there is, what is the recipe using what is available) for the following triggering condition

```yaml
on:
  release:
    types: [published]
```

of course, the release will correspond to a tag (which is usually the name of the release itself), so this is a superset of 

```yaml
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
```

P.S: I am using this action within the [Docker Build and push action](https://github.com/marketplace/actions/build-and-push-docker-images)

The idea is to have a app:latest which always points to the latest release, but also explicit versions to retrieve environments built in previous releases, so app:vX.Y.Z
