### ISSUE TITLE
Comments in tags input are treated as tags literally

### ISSUE THREAD

**Issue by pallxk** [docker/metadata-action#169]
### Behaviour

Comments (`# ...`) in tags input are treated as tags literally. They should be ignored; this syntax is also used extensively in the snippets in `README.md`.

If comments in tags are supposed to be treated literally, then the use of it in snippets in README can be confusing for newcomers.

#### Steps to reproduce this issue

Simply trigger the workflow using the configuration below.

#### Expected behaviour

`# minimal` should be ignored and not parsed as a docker tag.

#### Actual behaviour

`# minimal` parsed as a docker tag, and use it in later steps cause errors as `test:# minimal` is not a valid repository/tag.

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: test
          tags: |
            # minimal
            type=edge
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs)
> and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

[logs_7.zip](https://github.com/docker/metadata-action/files/8158689/logs_7.zip)
