### ISSUE TITLE
Latest tag is added only for master branch by default, not for main

### ISSUE THREAD

**Issue by mvadu** [docker/metadata-action#171]
### Behaviour
per readme, `For conditionally tagging with latest for a specific branch name, e.g. if your default branch name is not *master*, use type=raw with a boolean expression:` this seems to ignore merges to current github standard of `main` 

#### Steps to reproduce this issue

1. setup `metada-action` with `latest` tag handling left as default
2. merge a PR to main (default branch)

#### Expected behaviour
`latest` tag should be added for `main` merges not just old `master`

#### Actual behaviour
[image was tagged as main not as latest](https://github.com/AdysTech/mi_atc_reader/runs/5440343790?check_suite_focus=true#step:5:44)
### Configuration

* Repository URL (if public): 
https://github.com/AdysTech/mi_atc_reader

* Build URL (if public): 
https://github.com/AdysTech/mi_atc_reader/runs/5440343790?check_suite_focus=true#step:5:44

```yml
env:
  #REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
     - name: Retrieve author data
        run: |
          echo AUTHOR=$(curl -sSL ${{ github.event.repository.owner.url }} | jq -r '.name') >> $GITHUB_ENV
      #https://github.com/docker/metadata-action
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: ${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.authors=${{ env.AUTHOR }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
```
