### ISSUE TITLE
runNumber is empty when running workflow manually

### ISSUE THREAD

**Issue by mahmoudhossam** [docker/metadata-action#177]
#### Steps to reproduce this issue

1. try to use `runNumber` in a tag with `type=raw`
2. run workflow

#### Expected behaviour

`runNumber` should be populated since it exists in the context

#### Actual behaviour

`runNumber` is empty

### Configuration

```yml
name: workflow

on:
  push:
    branches:
      - dev
      - stage
      - master
    tags:
      - "**"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Github container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}
      - name: Tag Docker image
        id: tag
        uses: docker/metadata-action@v3
        with:
          images: ${{ steps.build.outputs.imageid }}
          # branch-trunc(commit_hash)
          # branch-RUN_NUMBER
          tags: |
            type=raw,value={{branch}}-{{sha}},priority=200
            type=raw,value={{branch}}-{{runNumber}},priority=100
      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.tag.outputs.tags }}
```

### Logs
[2.txt](https://github.com/docker/metadata-action/files/8332859/2.txt)
