### ISSUE TITLE
Slash in tag converted to hyphen

### ISSUE THREAD

**Issue by aaronadamsCA** [docker/metadata-action#189]
#### Steps to reproduce this issue

1. Use `tags: type=match,pattern=devcontainer/v(.*),group=1`.
2. Push tag `devcontainer/v1.0.0`.

#### Expected behaviour

Docker image version is `1.0.0`.

#### Actual behaviour

```
Warning: devcontainer/v(.*) does not match devcontainer-v1.0.0.
Warning: No Docker image version has been generated. Check tags input.
Warning: No Docker tag has been generated. Check tags input.
```

Directory separator `/` is transformed to a hyphen `-`. This is unexpected and (I'm pretty sure) undocumented, so it should either be fixed or documented. Thanks!

### Configuration

```yml
name: Build and push development container image
on:
  push:
    tags:
      - devcontainer/v*
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3.0.1

      - uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: arm64

      - uses: docker/setup-buildx-action@v1.6.0

      - uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v3.7.0
        with:
          images: ghcr.io/${{ github.repository }}/devcontainer
          # This is the line that isn't working
          tags: type=match,pattern=devcontainer/v(.*),group=1

      - uses: docker/build-push-action@v2.10.0
        with:
          context: .devcontainer
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
```
