### ISSUE TITLE
Use correct commit sha for PRs?

### ISSUE THREAD

**Issue by evandam** [docker/metadata-action#206]
### Behaviour

Hey folks, similar to https://github.com/docker/metadata-action/issues/191 a bit, when running a workflow on a PR event, the `{{ sha }}` refers to the temporary merge commit to the target branch, not the commit that was pushed to trigger the event.

I realize this is a pretty common situation with GitHub actions, but it ends up with Docker tags/labels that don't map back to any real commits. It would be really useful if this action automatically used `github.event.pull_request.head.sha` for PR events. I think it would have to be set for the tags `{{ sha }}` value and the auto-generated label `org.opencontainers.image.revision`.

I'm aware we can work around the tags situation by using `type=raw` and passing a value based on `github.event.pull_request.head.sha`, but it feels a bit error-prone.

I'm unaware of a workaround for overriding the `org.opencontainers.image.revision` label, though.

#### Steps to reproduce this issue

See example workflow and run on a PR

#### Expected behaviour

Tags with the correct sha in a PR (same with org.opencontainers.image.revision label)

#### Actual behaviour

Tags are created with the merge commit of the PR to the target branch (same with org.opencontainers.image.revision)

```yml
name: AWS

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: "my-repo/my-image"
          tags: |
            type=ref,event=branch,suffix=-{{ sha }}
            type=ref,event=pr,suffix=-{{ sha }}
```

**Comment by crazy-max** [comment]
> the `{{ sha }}` refers to the temporary merge commit to the target branch, not the commit that was pushed to trigger the event.

No, `{{sha}}` refers to the commit SHA that triggered the workflow run. It's the same as `GITHUB_SHA` or `${{ github.sha }}` in [github context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context).

You can check this behavior by adding the following step in your workflow to trace the context:

```yaml
      - name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
```

In your case you might want `${{ github.event.pull_request.head.sha }}` or `${{ github.event.pull_request.base.sha }}`:

```yaml
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: "my-repo/my-image"
          tags: |
            type=ref,event=branch,suffix=-{{ sha }}
            type=ref,event=pr,suffix=-${{ github.event.pull_request.head.sha }}
```

> when running a workflow on a PR event

Also on PR event your don't have access to secrets so you don't push your image anyway? Maybe it's a private repo and you're using OIDC?

**Comment by crazy-max** [comment]
> but unaware of anything for labels and it's just a tricky thing to have to account for whenever we want to reference the git sha.

Sorry I missed your case with labels. So yes you can override them with:

```yaml
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: "my-repo/my-image"
          tags: |
            type=ref,event=branch,suffix=-{{ sha }}
            type=ref,event=pr,suffix=-${{ github.event.pull_request.head.sha }}
          labels:
            org.opencontainers.image.revision=${{ github.event.pull_request.head.sha }}
```
