### ISSUE TITLE
Why manually triggered build doesn't get tags generated?

### ISSUE THREAD

**Issue by pmalek** [docker/metadata-action#211]
#### Expected behaviour

Working build: https://github.com/Kong/kubernetes-ingress-controller/runs/6620050385?check_suite_focus=true#step:8:26

```
Processing tags input
  type=schedule,pattern=nightly,enable=true,priority=1000
  type=schedule,pattern={{date 'YYYY-MM-DD'}},enable=true,priority=1000
Processing flavor input
Docker image version
  nightly
Docker tags
  kong/nightly-ingress-controller:nightly
  kong/nightly-ingress-controller:2022-05-27
```

#### Actual behaviour

Broken build (manually triggered):  https://github.com/Kong/kubernetes-ingress-controller/runs/6627164755?check_suite_focus=true#step:8:37

### Configuration

* Repository URL (if public): https://github.com/Kong/kubernetes-ingress-controller/blob/e8903746fa6a6992c39e09e56b9538275054ed86/.github/workflows/nightly.yaml#L13-L54
* Build URL (if public): added in Actual/Expected behaviour section

```yml
      - name: Add standard tags
        run: |
          echo 'TAGS_STANDARD<<EOF' >> $GITHUB_ENV
          echo 'type=schedule,pattern=nightly' >> $GITHUB_ENV
          echo "type=schedule,pattern={{date 'YYYY-MM-DD'}}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
...
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: kong/nightly-ingress-controller
          tags: ${{ env.TAGS_STANDARD }}
```

### Open questions

Why manually triggered build doesn't get tags generated?

**Comment by crazy-max** [comment]
@pmalek That's because you only have `type=schedule` entries which are only generate on `schedule` event. Looking at the events of your workflow:

```yaml
on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch: {}
```

I would say you can just use `type=raw`:

```yaml
      - name: Add standard tags
        run: |
          echo 'TAGS_STANDARD<<EOF' >> $GITHUB_ENV
          echo 'type=raw,value=nightly' >> $GITHUB_ENV
          echo "type=raw,value={{date 'YYYY-MM-DD'}}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Add Red Hat standard tags
        run: |
          echo 'REDHAT_STANDARD<<EOF' >> $GITHUB_ENV
          echo 'type=raw,value=nightly,suffix=-redhat' >> $GITHUB_ENV
          echo "type=raw,value={{date 'YYYY-MM-DD'}},suffix=-redhat" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
```
