### ISSUE TITLE
Pass tags as unmasked output to other job

### ISSUE THREAD

**Issue by dklor** [docker/metadata-action#214]
Hi together, I have a workflow with two jobs: In the first one I make use of the metadata action to build a custom docker image and push it to an Azure Container Registry:
``` yml
build-and-push-image:
   runs-on: self-hosted
   env:
     CONTAINER_REGISTRY: myregistry.azurecr.io

   steps:
     ...

     - name: Extract metadata (tags, labels) for Docker
       id: meta
       uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
       with:
         images: ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}

     - name: Build and push Docker image
       uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
       with:
         context: .
         push: true
         tags: ${{ steps.meta.outputs.tags }}
         labels: ${{ steps.meta.outputs.labels }}

   outputs:
     tags: ${{ steps.meta.outputs.tags }}
```

In the second job I want to deploy the previously built image to an Azure Container App by referencing the image tag created by the metadata action which I declared in the outputs section of the first job:

``` yml
deploy:
  runs-on: self-hosted
  needs: build-and-push-image

  steps:
    ...

    - name: Deploy to containerapp
      run: |
        az config set extension.use_dynamic_install=yes_without_prompt
        az containerapp update -n myapp -g myrg -i ${{ needs.build-and-push-image.outputs.tags}}
```
Unfortunately, the output is skipped with the following warning:
![image](https://user-images.githubusercontent.com/25993523/172901951-632f7b56-0b75-4df3-8fc8-ec82f189c3c5.png)

Is there any way I can avoid that skip? I assume the reason for this is that you mask the tags output, but from my point of view the tag does not contain any sensitive information. Other actions like [configure-aws-credentials](https://github.com/aws-actions/configure-aws-credentials/blob/master/action.yml) provide input arguments to control if certain outputs should be masked or not. Maybe this could be a consideration for this action as well.

For now, I will merge both jobs into one as a workaround. However, this makes my setup less reusable for the future, where I would like to make use of the [reusable workflows feature](https://docs.github.com/en/actions/using-workflows/reusing-workflows) to be able to call workflows individually.
