### ISSUE TITLE
Use output value from another step

### ISSUE THREAD

**Issue by jessekrubin** [docker/metadata-action#222]
How do I use the output of another step as a tag component?

```
      - name: Set version
        id: pkgversion
        run: |
          echo '::set-output name=PKG_VERSION::$(jq -r ".version" "package.json")'
      - name: echo version
        run: |
          echo "version is ${{ steps.pkgversion.outputs.PKG_VERSION }}"
        - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: dynamicgraphics/predators2-dev
          tags: |
            type=raw,value=latest
            type=raw,value=dev-{{date 'YYYYMMDD'}}-{{sha}}
            type=raw,value=dev-${{ steps.pkgversion.outputs.PKG_VERSION }}

```

I get "double quoted something or other went wrong..." as an error

**Comment by crazy-max** [comment]
Can you post a link to your workflow please? Or logs might help too.

**Comment by jessekrubin** [comment]
Either this has resolved it self? or I did something to fix something wrong on my end, but it works now. 

Repro-repo: https://github.com/jessekrubin/docker-metadata-action-222

**Comment by crazy-max** [comment]
Nothing on our end but looking at your workflow with previous failed attempt:

```yaml
name: DGCI

on: [ push, pull_request ]
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set version
        id: pkgversion
        run: |
          PKG_VERSION=$(jq -r ".version" "package.json")
          echo "$PKG_VERSION"
          echo "::set-output name=PKG_VERSION::$PKG_VERSION"
      - name: echo version
        run: |
          echo "version is ${{ steps.pkgversion.outputs.PKG_VERSION }}"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: someimage
          tags: |
            type=raw,value=latest
            type=raw,value=dev-{{date 'YYYYMMDD'}}-{{sha}}
            type=raw,value=dev-${{ steps.pkgversion.outputs.PKG_VERSION }}
      - name: echo docker meta
        id: echo-docker-meta
        run: |
          echo ${{ steps.pkgversion.outputs.PKG_VERSION }}
          echo ${{ steps.meta.outputs.tags }}
```

```
0.1.0
someimage:latest
/home/runner/work/_temp/8c3324de-0c7a-4672-b804-1d7c0e91dfa0.sh: line 3: someimage:dev-20220726-a5c30ca: command not found
```
> https://github.com/jessekrubin/docker-metadata-action-222/runs/7524265486?check_suite_focus=true#step:6:10

That's because `${{ steps.meta.outputs.tags }}` is a multiline string so when echoing the shell will interpret following lines as command.

You can change the `tags` output separator with the [`sep-tags` input](https://github.com/docker/metadata-action#inputs):

```yaml
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: someimage
          sep-tags: ","
          tags: |
            type=raw,value=latest
            type=raw,value=dev-{{date 'YYYYMMDD'}}-{{sha}}
            type=raw,value=dev-${{ steps.pkgversion.outputs.PKG_VERSION }}
```

Closing this issue since that should answer your question, but feel free to re-open if it doesn't. Thanks.
