### ISSUE TITLE
latest tag not created

### ISSUE THREAD

**Issue by jenshorch** [docker/metadata-action#223]
Hi all,

I have trouble to get latest tag working. 
I want latest tag to be created only on master branch. But I can´t get it to work. 
On develop branch we tag our commits with 'prerelease-x.y.z' resulting in docker images tagged with this tag.
On master branch we tag our commits with 'vx.y.z'. In this case we want to tag the docker image with latest in addition.

Here my config:

```yml
- name: Extract metadata (tags, labels) for Docker
   id: meta
   uses: docker/metadata-action@v2
   with:
     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
     flavor: |
       latest=${{ endsWith(github.ref, github.event.repository.default_branch) }}
     tags: |
       type=ref,event=tag
```

No matter if running on master or not, logs for metadata action shows always this:
```
Processing flavor input
  latest=false
  prefix=
  suffix=
```

I tried this too but with no success.
```
- name: Extract metadata (tags, labels) for Docker
   id: meta
   uses: docker/metadata-action@v2
   with:
     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
     flavor: |
       latest=false
     tags: |
       type=ref,event=tag
       type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
```

Any ideas what I´m doing wrong?
