### ISSUE TITLE
Only a single tag is created

### ISSUE THREAD

**Issue by thisismydesign** [docker/metadata-action#227]
#### Steps to reproduce this issue

On v4 I want to have multiple tags, e.g. for sha and branch, but whatever input I provide, only a single tag is generated.

```
name: PR Lint & Test & Build
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE }}
          tags: |
            type=raw,value={{branch}}
            type=raw,value={{sha}}
```

Output:
```
Processing tags input
  type=raw,value=***branch***,enable=true,priority=200
  type=raw,value=***sha***,enable=true,priority=200
...
Docker tags
  eu.gcr.io/.../...:657c8de
```

Tried with other types, such as `ref` and `sha`, same result.

#### Expected behaviour

Multiple tags are created

#### Actual behaviour

Only a single tag is created.

### Configuration

Repo is private
