### ISSUE TITLE
Setting sep-tags to ' ' does not take effect, tag separator remains a newline

### ISSUE THREAD

**Issue by sml-virta** [docker/metadata-action#229]
### Behaviour

When setting `with: sep-tags: ' '` (a string containing a single space character), the separator is ignored, and the action continues to separate the tags with a newline instead.

Setting `sep-tags` to some other string, such as `xxx`, works as expected.

>My theory is that the call to `core.getInput` on [this line](https://github.com/docker/metadata-action/blob/b2391d37b4157fa4aa2e118d643f417910ff3242/src/context.ts#L34) is returning a falsy value when it retrieves a string that contains only whitespace.

Given that setting this value to `' '` is probably the most plausible use case for `sep-tags`, I would expect this to work correctly. For now my workaround will have to be to use `sed` to convert the newlines to spaces for the rest of my scripting to consume.

#### Steps to reproduce this issue

1. Set `sep-tags` to `' '`

#### Expected behaviour

The tags in the output should be separated by a single space.

#### Actual behaviour

The tags are separated by a newline, as if we did not set `sep-tags`.

### Configuration

```yml
      - name: Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@v4
        with:
          images: <redacted>
          sep-tags: ' '
          tags: |
            type=sha,prefix=,format=long
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
```

### Logs

```
/home/runner/work/_temp/799388a1-9005-4fc6-b15d-98325a4d5ee6.sh: line 3: syntax error near unexpected token `<redacted>:ee0b30872d08ca855a7016346493cee176f3bdac'
<redacted>:ee0b30872d08ca855a7016346493cee176f3bdac
```
