### ISSUE TITLE
use `tags: type=semver` on `release` event

### ISSUE THREAD

**Issue by kaznovac** [docker/metadata-action#240]
I'd like to generate `semver` version tags for the github's `release` event

```yaml
on:
  release:
    types:
      - published

jobs:
  docker-build:
    # ...
    steps:
      # ...
      -
        name: Extract Docker metadata ${{ env.IMAGE_NAME }}
        id: docker-meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}

```

e.g. on the `v1.2.3` release completed I'd like these tags to be generated:
`1.2.3`, `1.2`, `1`, `sha-XXX`, `latest` (it would be great if this can be conditioned by the tag actually being the latest version)

related: #168
