### ISSUE TITLE
Would you consider ref tag type without event?

### ISSUE THREAD

**Issue by Colin-b** [docker/metadata-action#253]
#### Steps to reproduce this issue

Execute the action with only the ref tag type:
`
tags: |
            type=ref
`

#### Expected behaviour

Depending on the event, it should select the appropriate event type.
On a tag push, select the tag event type.
On a branch push, select the branch event type.

#### Actual behaviour

For now it fails with `Missing event attribute for type=ref`

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
on:
  push:
jobs:
  demo:
    steps:
      # Setup
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  # v3.0.2
      - uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea  # v4.1.1
        with:
          images: my_dummy_image
          tags: |
            type=ref
```

### Logs

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs)
> and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.
