### ISSUE TITLE
[Error] Using `tz=` in `type=ref` tag

### ISSUE THREAD

**Issue by ZaneH** [docker/metadata-action#255]
### Behaviour

```yaml
[...]
tags: |
    type=ref,event=branch,priority=1001,suffix=.{{date 'YYYY-MM-DD' tz='America/New_York'}}
[...]
```

Produces an error when using `tz=`. Removing the option resolves the problem but uses UTC.

```
Error: Parse error on line 1:
...{{date 'YYYY-MM-DD' tz
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
```

#### Steps to reproduce this issue

1. Use `docker/metadata-action`
2. Add a tag of type `ref`, `event=branch` and add a {{date}} somewhere in the tag
3. Add the `tz=` option to the {{date}} and watch for errors.

#### Expected behaviour

I wanted to be able to specify the timezone to be America/New_York explicitly.

#### Actual behaviour

Workflow fails because of the error above.

### Configuration

* Repository URL (if public): n/a
* Build URL (if public): n/a

```yml
# ./.github/workflows/release.yml
name: Update Harbor Image

on:
    push:
        branches: [master, main, gha-testing]
    workflow_dispatch:

env:
    # For Harbor
    REGISTRY_URL: [snip]
    PROJECT_NAME: [snip]
    REPO_NAME: [snip]

jobs:
    update-harbor-image:
        name: Update Harbor Image
        runs-on: sat-hosted
        steps:
            - uses: actions/checkout@v3

            - uses: actions/checkout@v3
              with:
                  repository: my-org/org-actions
                  path: org-actions

            - name: Docker Login
              uses: ./org-actions/docker-login
              with:
                  username: ${{ secrets.HARBOR_USERNAME }}
                  password: ${{ secrets.HARBOR_PASSWORD }}
                  registry-url: ${{ env.REGISTRY_URL }}

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: |
                      ${{ env.REGISTRY_URL }}/${{ env.PROJECT_NAME }}/${{ env.REPO_NAME }}
                  tags: |
                      type=ref,event=branch,priority=1001,suffix=.{{date 'YYYY-MM-DD' tz='America/New_York'}}
                      type=schedule,pattern={{date 'YYYY-MM-DD' tz='America/New_York'}}
                      type=semver,pattern={{raw}}
                      type=sha

            - uses: ./org-actions/update-image
              name: Update [snip] Docker image
              with:
                  image-tag: ${{ steps.meta.outputs.tags }}
```

### Logs

n/a
