### ISSUE TITLE
Issue parsing strings from matrix

### ISSUE THREAD

**Issue by rockstorm101** [docker/metadata-action#260]
Not sure if this is a problem within metadata when parsing the string or the problem is with the matrix feature or maybe I'm simply abusing the feature here.

#### Steps to reproduce this issue

Run the following action which has a multi-line string in one of its arguments:

```yaml
name: Test Metadata
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [master]
        include:
          - branch: master
            tags: |
              type=raw,priority=900,value=4.2.2
              type=raw,priority=700,value=4.0
              type=raw,priority=500,value=4
    steps:
     - name: Set Metadata
       id: meta
       uses: docker/metadata-action@v4
       with:
         images: user/example
         tags: ${{ matrix.tags }}|
     - name: Echo Results
       run: |
         echo "Branch '${{ matrix.branch }}' has tags:"
         echo "${{ steps.meta.outputs.tags }}"
```

#### Expected behaviour

The echoes at the end should simply print 3 tags:
```
Branch 'master' has tags:
user/example:4.2.2
user/example:4.0
user/example:4
```

#### Actual behaviour

However a spurious fourth tag is added to the list:
```
Branch 'master' has tags:
user/example:4.2.2
user/example:4.0
user/example:4
user/example:-
```

The (hopefully) relevant parts of the pertaining the Metadata action. Note the spurious 4th input tag with value "|".
```
> Processing tags input
  type=raw,priority=900,value=4.2.2,enable=true
  type=raw,priority=700,value=4.0,enable=true
  type=raw,priority=500,value=4,enable=true
  type=raw,value=|,enable=true,priority=200
[...]
> Docker tags
  user/example:4.2.2
  user/example:4.0
  user/example:4
  user/example:-
```

Thanks in advance, let me know if I can help debug any further.
