### ISSUE TITLE
Flavor is ignored in output, despite being parsed properly

### ISSUE THREAD

**Issue by fardog** [docker/metadata-action#270]
### Behaviour

Even though I've specified a `flavor` which contains a prefix, and it is parsed properly, it doesn't result in a prefix on the docker tags which are produced. This prefix is being used in a `matrix` to allow two different packages to be built into images. Apologies if I'm missing something obvious (it feels like I must be?).

I'm using the following flavor:

```
          flavor: |
            latest=auto
            prefix=${{ matrix.package }}-,onlatest=true
            suffix=
```

I've tried this with a few different combinations, including both [with tags specified](https://github.com/fardog/primebot/actions/runs/4332624631/jobs/7565241206) and [without](https://github.com/fardog/primebot/actions/runs/4332602806/jobs/7565203084), as well as messing with the `onlatest`, but none of this appears to change the behavior.

Thanks tons!

#### Steps to reproduce this issue

1. Configure the workflow with a `flavors` defined, which specifies a prefix
2. Run the action
3. Observe incorrect output

#### Expected behaviour

Docker tags should be generated with a prefix; in the case of the above, it should be `ghcr.io/fardog/primebot:twitter-pr-12`.

#### Actual behaviour

Docker tags ignore the prefix; e.g. `ghcr.io/fardog/primebot:pr-12`

### Configuration

* Repository URL (if public): https://github.com/fardog/primebot/pull/12
* Build URL (if public): https://github.com/fardog/primebot/actions/runs/4332624631/jobs/7565241206

The repository URL contains a few different attempts within that PR, none of the configs I attempted were successful however.

```yml
name: Docker Image

on:
  push:
    branches: 
      - master
    tags:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    strategy:
      matrix:
        package: ["twitter", "mastodon"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
            prefix=${{ matrix.package }}-,onlatest=true
            suffix=
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-${{ matrix.package }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

### Logs

[logs_32.zip](https://github.com/docker/metadata-action/files/10889605/logs_32.zip)

Attached; also here is a screenshot of relevant output.

![image](https://user-images.githubusercontent.com/2207657/222927016-0082e0e2-ca35-4e0b-a186-7be24c33ce42.png)

**Comment by crazy-max** [comment]
Yes indeed. `type=sha` already has a default prefix `sha-` and `type=ref,event=pr` with `pr-` prefix. Therefore a global prefix can't be applied atm.

I think we could allow a global prefix being set if value is empty, like:

```yaml
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
            prefix=${{ matrix.package }}-,onlatest=true
            suffix=
          tags: |
            type=ref,event=pr,prefix=
            type=sha,prefix=
```

WDYT?

**Comment by fardog** [comment]
oh i see; yes, it was unexpected that `sha-` and `pr-` _were_ already prefixes, so while i was expecting my prefix value to be written to all output, it was getting overwritten by this implicit default.

i think your workaround is probably a better solution than requiring the empty prefix, at least as it stands today. i think what i'd prefer is for the prefix to only be user-provided, and `ref` and `sha` to be instead part of the tag, so the prefix works as expected across all tags; i think the implicit prefix of the `ref` and `sha` creates unexpected behavior.

as this is my first use of this action though, i'm probably not best qualified to decide what's expected or unexpected, just my opinion. your workaround has helped me understand the problem and solved my issue; I super appreciate it. i'll leave this ticket open in case it's something you want to address, or feel free to close if not.

**Comment by crazy-max** [comment]
@fardog I think I will do another implementation using a `mode` attr to prefix/suffix flavors like:

```yaml
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
            prefix=${{ matrix.package }}-,onlatest=true,mode=replace
            suffix=
          tags: |
            type=ref,event=pr
            type=sha
```

`mode` could be `auto`, `merge`, `replace` (defaults to `auto`):
* `auto`: current behavior, set prefix/suffix is not already set in `tags`
* `merge`: if prefix/suffix is already set, then append (suffix) / prepend (prefix)
* `replace`: if prefix/suffix is already set, then replace it with global one

WDYT?
