### ISSUE TITLE
Is it possible to check if a tag is a pre-release?

### ISSUE THREAD

**Issue by m90** [docker/metadata-action#276]
I would like to model a release workflow that looks like this:

- a tag (e.g. `v2.2.3`) is pushed to a repository
- the image is built and tagged as:
  - `v2.2.3`
  - `v2`
  - `latest`

This works as expected, however I am not able to cover an exception I would like to make here, which is excluding pre-releases and such. For example I would like to cover:

- a tag (e.g. `v2.3.0-rc.12`) is pushed to a repository
- the image is built and tagged as:
  - `v2.3.0-rc.12`
 
i.e. `v2` and `latest` are omitted in this case.

My current step configuration looks like this:

```yml
- name: Extract metadata (tags, labels) for Docker
  id: meta
  uses: docker/metadata-action@v4
  with:
    flavor: |
      latest=false
    tags: |
      type=semver,pattern={{raw}}
      type=semver,pattern=v{{major}},enable=${{ <what goes here?> }}
      type=raw,value=latest,enable=${{ <what goes here?> }}
    images: |
      something/something
      ghcr.io/${{ github.repository }}
```

but obviously I am unable to conditionally enable `v{{major}}` and `latest` tags according to my needs. Is there a built-in way to do this or do I need to resort to scripting this logic myself something like this:

```yml
- name: Extract Docker tags
  id: meta
  run: |
    version_tag="${{github.ref_name}}"
    tags=($version_tag)
    if [[ "$version_tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      # prerelease tags like `v2.0.0-alpha.1` should not be released as `latest` nor `v2`
      tags+=("latest")
      tags+=($(echo "$version_tag" | cut -d. -f1))
    fi
    releases=""
    for tag in "${tags[@]}"; do
      releases="${releases:+$releases,}something/something:$tag,ghcr.io/something/something:$tag"
    done
    echo "releases=$releases" >> "$GITHUB_OUTPUT"
```
