### ISSUE TITLE
Rebuild semver tags on schedule

### ISSUE THREAD

**Issue by ntarocco** [docker/metadata-action#282]
Is it possible to rebuild existing tags on schedule?

In our repo, when we create a new tag, e.g. `v1.0.3`, we publish the following Docker images:

- `myimage:1`
- `myimage:1.0`
- `myimage:1.0.3`

This is to allow users to always use the latest image of a given major version. Often, users, will simply use `myimage:1`.

I would like, every night/week, to run a GitHub CI jon (`on schedule`) that will re-publish these 3 Docker images: we do this to run`rpm/apt update` and get the latest security patches. We would like basically to overwrite such publish images.

At the moment, I have this `on tag`:
```yaml
- name: Extract GIT metadata for Docker
  id: meta
  uses: docker/metadata-action@v4
  with:
    images: ...
    tags: |
      type=semver,pattern={{major}}
      type=semver,pattern={{major}}.{{minor}}
      type=semver,pattern={{major}}.{{minor}}.{{patch}}
      type=semver,pattern={{version}}
```

I have already created a `matrix` that will run on each tag reading a file or via a `git` cmd, which I can use it for the `enable`. What I am missing is the possibility of taking advantage of the `major/minor/version` patterns on schedule or raw.
Is there a way or I have to script it in GitHub actions?

**Comment by ntarocco** [comment]
For other readers, if needed. For the time being, I came up with this:

```yaml
    strategy:
      matrix:
        tag: [v1,v2]

    steps:
      ...
      - name: Get latest tag starting with ${{ matrix.tag }}
        run: echo "::set-env name=TAG::$(git tag -l --sort -version:refname | head -n 1 | grep -o '^${{ matrix.tag }}.*')"
      ...
      - name: Extract semver
        run: |
          if [[ "${{ env.TAG }}" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            ::set-env name=MAJOR::${BASH_REMATCH[1]}
            ::set-env name=MINOR::${BASH_REMATCH[2]}
            ::set-env name=PATCH::${BASH_REMATCH[3]}
            ::set-env name=VERSION::$MAJOR.$MINOR.$PATCH
          fi

       - name: Extract GIT metadata for Docker
        uses: docker/metadata-action@v4
        with:
          images: ...
          tags: |
            type=raw,value=${{ env.MAJOR }}
            type=raw,pattern=${{ env.MAJOR }}.${{ MINOR }}
            type=raw,pattern=${{ env.MAJOR }}.${{ MINOR }}.${{ PATCH }}
            type=raw,pattern=${{ env.VERSION }}
            type=schedule,pattern={{date 'YYYYMMDD'}}
          flavor: |
            latest=true
```

**Comment by crazy-max** [comment]
It should work if you use the [`context` input](https://github.com/docker/metadata-action#context-input):

```yaml
name: nightly

on:
  schedule:
    - cron: "0 10 * * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - v1.0.3
          - v1.0.4
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.tag }}
      -
        name: Docker meta
        id: meta
        # use master branch for now, context input feature is not released yet
        uses: docker/metadata-action@master
        with:
          context: git
          images: |
            name/app
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
```

Also the following:

```
type=semver,pattern={{major}}.{{minor}}.{{patch}}
type=semver,pattern={{version}}
```

Can be just:

```
type=semver,pattern={{version}}
```
