### ISSUE TITLE
`metadata-action` fails to pull LABELs from Dockerfile

### ISSUE THREAD

**Issue by SimplicityGuy** [docker/metadata-action#295]
#### Steps to reproduce this issue

1. create a Dockerfile with opencontainer LABELs specified
2. utilize the action to pull metadata
3. notice the output does not include the LABELs set in the Dockerfile

#### Expected behaviour

The LABELs from the Dockerfile are used first.

#### Actual behaviour

The LABELs from the Dockerfile are not used

### Configuration

* Repository URL (if public): https://github.com/SimplicityGuy/dockerfiles
* Build URL (if public): https://github.com/SimplicityGuy/dockerfiles/actions

```yml
name: discogsography

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/discogsography

jobs:
  list-sub-projects:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Get all sub-projects.
        id: set-matrix
        run: echo "::set-output name=matrix::$(ls -d discogsography/*/ | sed -r 's/discogsography//g' | sed -r 's/\///g' | jq -R -s -c 'split("\n")[:-1]')"

  build-discogsography:
    needs: list-sub-projects

    runs-on: ubuntu-latest

    strategy:
      matrix:
        sub-project: ${{ fromJson(needs.list-sub-projects.outputs.matrix) }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Log in to the GitHub Container Registry.
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker.
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.sub-project }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up Docker Buildx.
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64, linux/arm64, linux/arm/v7, linux/arm/v6

      - name: Build and push Docker image to GitHub Container Registry.
        uses: docker/build-push-action@v4
        with:
          context: discogsography/${{ matrix.sub-project }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

### Logs
```
  org.opencontainers.image.title=dockerfiles
  org.opencontainers.image.description=Docker image builds for various projects.
  org.opencontainers.image.url=https://github.com/SimplicityGuy/dockerfiles
  org.opencontainers.image.source=https://github.com/SimplicityGuy/dockerfiles
  org.opencontainers.image.version=latest
  org.opencontainers.image.created=2023-05-31T01:53:[40](https://github.com/SimplicityGuy/dockerfiles/actions/runs/5128006711/jobs/9224261058#step:4:47).721Z
  org.opencontainers.image.revision=1f35dc01f629400d5f0e2f2069c94f7971e8dc17
  org.opencontainers.image.licenses=MIT
```
