### ISSUE TITLE
Support for multiple raw tags in a single tags input line

### ISSUE THREAD

**Issue by stigok** [docker/metadata-action#298]
While using this action within a shared/reusable workflow, I see the need to let the consumers pass a list of additional tags for the images.
The problem is that I currently can't see a way to pass a **list** of raw tags to this action.

When attempting to use GitHub Actions builtin function `join` to join the tags with newlines, it outputs the string `\n` instead, which in turn is converted by this action to a dash `-`.

```yml
      -
        name: Generate image tags
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            ${{ inputs.registry-url }}/${{ inputs.name }}
          tags: |
            type=ref,event=pr,enable=${{ inputs.tag-pr }}
            type=ref,event=branch,enable=${{ inputs.tag-branch }}
            type=raw,value=${{ github.sha }},enable=${{ inputs.tag-sha }}
            type=raw,value=latest,enable=${{ inputs.tag-latest }}
            ${{ join(fromJSON(steps.additional-tags.outputs.tags), '\n') }}
```

I think I see the potential for a new tag type that can handle multiple named tags separated by some (possibly) custom delimiter.

```yml
        with:
          sep-raw-tags: '|'
          images: |
            ${{ inputs.registry-url }}/${{ inputs.name }}
          tags: |
            type=multiraw,value=tag1|tag2|tag3,enable=true
            type=multiraw,value=${{ join(fromJSON(steps.additional-tags.outputs.tags), '|') }}
```

I guess the existing `type=raw` can't be used for this, as it may change the current behaviour of simply replacing the `|` with a `-` here in this example.

Any thoughts for this feature request, or possibly other work-arounds I can work with instead?

**Comment by crazy-max** [comment]
https://github.com/docker/metadata-action#typeraw can already just be a list of tags without specifying the type:

```yaml
tags: |
  type=raw,value=foo
  type=raw,value=bar
  # or
  type=raw,foo
  type=raw,bar
  # or
  foo
  bar
```

**Comment by stigok** [comment]
But the problem I am facing is that I am unable to programatically print a newline-separated list using the `join` builtin. The resulting value is always printed on a single line, resulting in a single tag, instead of e.g. 3.

**Example**
```yml
tags: |
  ${{ join(fromJSON('["foo","bar","baz"]'), '\n') }}
```
`tags` input is now: `foo\nbar\nbaz`. The newlines are not expanded to actual newlines.
This action then converts unsupported characters to dashes (`-`), and the resulting output looks like this:

```
Docker tags
  cr.example.com/test:foo-nbar-nbaz
```

**Comment by crazy-max** [comment]
Looking at https://github.com/nrkno/github-workflow-docker-build-push/pull/29/files#diff-fde0e5d64aae13964fdda6d47af304cf1a7015cbc17e440ac4a5e662ee1d875eR218-R234

```yaml
      -
        name: Build list of additional tags
        shell: python
        id: additional-tags
        run: |
          import json
          import os
          import sys
          # Build a list by splitting comma-separated tags, then remove empty list items.
          tags = list(filter(None, '''${{ inputs.tag-extra }}'''.split(",")))
          # Output a condensed JSON string representing the list and write to Actions output.
          with open(os.environ["GITHUB_OUTPUT"], 'a') as outputs:
            print("tags=", end='', file=outputs)
            json.dump(tags, outputs, separators=(",", ":"))
            print("", file=outputs) # final newline
```

Instead of using python you could just use https://github.com/actions/github-script and set the output using the GitHub core API (not tested):

```yaml
      -
        name: Build list of additional tags
        id: additional-tags
        uses: actions/github-script@v6
        with:
          script: |
            core.setOutput('tags', "${{ inputs.tag-extra }}".split(",").join("\n"))
```
