### ISSUE TITLE
is it possible to have generic pre-release tags?

### ISSUE THREAD

**Issue by Sandros94** [docker/metadata-action#305]
I'm ferly new to CI/CD pipelines, so forgive me for my blasphemy.

Currently I'm doing something like this:
```yml
- name: Extract metadata for Docker image
    id: meta
    uses: docker/metadata-action@v4
    with:
      images: ${{ env.GHCR_IMAGE }}
      tags: |
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
```

But how I am able to keep a `rc`, `beta` and `alpha` generic tags always up to date, much like a `latest` tag?

I've been reading the `README` and #276, and if I understood them correctly atm we only manage specific version for pre-release tags.

How could we get something like:

<html>
<body>

Event | Ref | Docker Tags
-- | -- | --
push tag | refs/tags/v1.2.3 | 1.2.3, 1.2, latest
push tag | refs/tags/v2.0.8-rc.101 | 2.0.8-rc.101, rc
push tag | refs/tags/v2.1.2-beta.67 | 2.1.2-beta.67, beta

</body>
</html>

### Use case
In a CD fractioned ingress/load balancer this would help in gathering useful data for those pre-release versions.
Like: for those smaller projects that is enough to go production with `latest`, a full stack dev could route 95% of the traffic to it and the remaining 5% to a `rc` deploy, gathering useful information for final bug-fixing.
