### ISSUE TITLE
Feature request: git submodule context

### ISSUE THREAD

**Issue by pl4nty** [docker/metadata-action#310]
I build several git submodules in a monorepo. It would be helpful to use the submodule git context for generating metadata, instead of the monorepo's context. A `context-path` option might work, or assuming `context` is a git path if it isn't `git` or `workflow`.

**Comment by crazy-max** [comment]
I think we could add a separator to the `git` context following by the path you want to use. Something like:

```yaml
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          context: "git:foo"
```

Where `foo` is a submodule.

But then GitHub metadata attached to the Git context would be quite wrong imo so I'm not sure.
