### ISSUE TITLE
Unable to verify the first certificate

### ISSUE THREAD

**Issue by nikolai-in** [docker/metadata-action#313]
I am using gitea's act runner to run a workflow inside the docker container to build and push my docker image to my private registry in gitea with self-signed certificates. I have added my private CA to the docker container and actions like: `actions/checkout@v3`, `docker/login-action@v2`, `docker/build-push-action@v4` are working fine. But `docker/metadata-action@v4` fails with `unable to verify the first certificate`.

I understand that this is probably not a standard use case, but I cannot figure out a way to get this action to work with my setup. Any help would be greatly appreciated.

Here is my workflow.yaml file:
```yaml
name: ci

on:
  schedule:
    - cron: "0 10 * * 3"
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "latest"

jobs:
  docker:
    runs-on: ubuntu-latest-with-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          repository: ${{ github.repository }}
          token: ${{ secrets.GITEA_TOKEN }}
      - name: Docker meta
        id: meta
        uses: https://github.com/docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            gitea.example.com/${{ gitea.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v2
        with:
          config: buildkitd.toml
      - name: Login to Docker Hub
        uses: https://github.com/docker/login-action@v2
        with:
          registry: https://gitea.example.com/
          username: ${{ gitea.actor }}
          password: ${{ secrets.DOCKER_KEY }}
      - name: Build and push
        uses: https://github.com/docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

```
Output:
```
::error::request to https://gitea.example.com/api/v1/repos/username/repo failed, reason: unable to verify the first certificate
```

**Comment by crazy-max** [comment]
> I am using gitea's act runner to run a workflow inside the docker container

I never used act sorry I can't really help but if you could give more logs that would be a good start. Maybe you can find some help on https://github.com/nektos/act/issues.

**Comment by nikolai-in** [comment]
Thank you very much. Unfortunately, I couldn't find any issues similar to my current problem. 

I add my private ca to a docker container (gitea's act runner uses docker container instead of vm as github actions do) which runs actions, like this: 
```Dockerfile
COPY myCA.pem /usr/local/share/ca-certificates/local-ca.crt
RUN chown root:root /usr/local/share/ca-certificates/local-ca.crt \
    && chmod 644 /usr/local/share/ca-certificates/local-ca.crt \
    && update-ca-certificates
```

I have noticed that without `buildkitd.toml` the `build and push` step would fail with the error `x509: certificate signed by unknown authority`:
```toml
[registry."gitea.example.com"]
http = false
insecure = false
ca = ["/etc/docker/certs.d/example.com/ca.crt"]
```

I have also tried adding some environment variables to the step like this:
```yaml
- name: Docker meta
        id: meta
        uses: https://github.com/docker/metadata-action@v4
        env:
          DOCKER_CERT_PATH: /usr/local/share/ca-certificates/
          DOCKER_TLS_VERIFY: 0
...
```

**Comment by crazy-max** [comment]
`uses: https://github.com/docker/metadata-action@v4` does not look right, should be `uses: `docker/metadata-action@v4`.

Closing this one as this is out of scope for usage of this action. Please continue the conversation if you consider this is an issue with the action itself.

**Comment by v1b1** [comment]
@nikolai-in I had this problem recently with a self-signed root certificate with my container release workflow. I believe the issue stems from the metadata-action leveraging Node's trust store by default instead of the one on the container running the job.

This is how I got it to work:

```yaml
    - name: Setup BuildX
      uses: docker/setup-buildx-action@v3
      with:
        config-inline: |
          [registry."${{ env.DOCKER_REGISTRY }}"]
            ca = ["/usr/local/share/ca-certificates/local-ca.crt"]

    # OK, leverages container trust store
    - name: Login
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Container metadata
      id: meta
      uses: docker/metadata-action@v5
      env:
        # Force this action to use the container trust store
        NODE_OPTIONS: --use-openssl-ca
      with:
        images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_OWNER }}/${{ env.DOCKER_REPO }}
        tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}-latest
```
