### ISSUE TITLE
Unexpected tag is created for type=match

### ISSUE THREAD

**Issue by Janarthanan-03** [docker/metadata-action#325]
### Behaviour
I am trying to create a docker tag with regex pattern fetched from git tag using type=match. But along with the matched pattern I am getting extra latest tag.

#### Steps to reproduce this issue

  docker-meta:
    name: meta tag
    runs-on: ubuntu-latest
    steps:
      - name: 🏷️ Bake meta tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: testimage
          tags: |
            type=match, pattern=zzz_v(.*), enable=${{ github.ref_type == 'tag' }}

#### Expected behaviour

Should create a single tag with only matched pattern

#### Actual behaviour

![image](https://github.com/docker/metadata-action/assets/129252174/29a8c295-ba7a-46d4-adb8-66394e52d83b)

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
  docker-meta:
    name: meta tag
    runs-on: ubuntu-latest
    steps:
      - name: 🏷️ Bake meta tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: testimage
          tags: |
            type=match, pattern=zzz_v(.*), enable=${{ github.ref_type == 'tag' }}
```

### Logs
Can be seen in attached image
