### ISSUE TITLE
Disable `main` tag when `latest` is enabled

### ISSUE THREAD

**Issue by rob93c** [docker/metadata-action#347]
### Description

While working on [my Docker workflow](https://github.com/Stickerifier/Stickerify/blob/main/.github/workflows/docker-image.yml), I noticed that when merging changes to my `main` (the default branch in my case) 2 tags are created: `latest` and `main`.

How can I prevent `main`'s creation?

This is my configuration:
````yaml
      - name: Extract metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            rob93c/stickerify
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
````
