### ISSUE TITLE
Secrets exposed in some action output

### ISSUE THREAD

**Issue by grahamalama** [docker/metadata-action#354]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/metadata-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

Despite secrets being masked in what's provided as input to this action, those same secrets are exposed in some of the output of the action.

### Expected behaviour

When I set a repo secret and use the secret in the action, it is masked throughout whatever output the action emits.

Secrets are masked in "Processing images input 👍🏻

<img width="492" alt="image" src="https://github.com/docker/metadata-action/assets/20747904/b3b32501-cc95-487c-bd3f-ecf3576deee6">

### Actual behaviour

The secrets are masked in the inputs and in some output, but they are not masked in all of the output, e.g.

<img width="577" alt="image" src="https://github.com/docker/metadata-action/assets/20747904/98906495-66ad-4f83-a0fd-f4ee46b0fd85">

### Workflow run URL

https://github.com/grahamalama/remote-settings/actions/runs/6707922537/job/18227548671

### YAML workflow

```yaml
- name: Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            mozilla/remote-settings
            ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPOSITORY }}/remote-settings
          tags: |
            type=raw,value=${{ env.LATEST_TAG }}
            type=raw,value=latest
```
