### ISSUE TITLE
Images cannot be empty as documentation suggests

### ISSUE THREAD

**Issue by olee** [docker/metadata-action#379]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/metadata-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

The documentation describes that `images` input can be empty so that only tags are generated:
https://github.com/docker/metadata-action/blob/releases/v4/README.md#images-input

However, when actually not defining `images`, github will complain because the property is set as required and defining it as an empty string will also result in the same error message:
`Error: images input required`

This can also be observed in the action definiton as required is set to true:
https://github.com/docker/metadata-action/blob/releases/v4/action.yml#L14-L16

Here an example step which will result in the error:
```yaml
      - id: meta
        uses: docker/metadata-action@v4
        with:
          tags: |
            type=sha
```

### Expected behaviour

The `images` input is not defined as required and works as the documentation describes

### Actual behaviour

`Error: images input required`

### YAML workflow

```yaml
jobs:
  build_and_push_images:
    steps:
      - id: meta
        uses: docker/metadata-action@v4
        with:
          tags: |
            type=sha
```

### Workflow logs

```
Run docker/metadata-action@v[4](https://github.com/..../..../actions/runs/..../job/....#step:7:4)
  with:
    images:  
    tags: type=sha
  type=ref,event=pr
  type=ref,event=branch
  type=semver,pattern={{version}}
  type=semver,pattern={{major}}.{{minor}}
  type=semver,pattern={{major}},enable=true
  
    context: workflow
    github-token: ***
Error: images input required
```
