### ISSUE TITLE
v5.5.0 Broke docker/bake-action with docker-metadata-action

### ISSUE THREAD

**Issue by mldmelissa** [docker/metadata-action#380]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/metadata-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

Bumping the version from 5.4.0 to 5.5.0 broke the usage of target "docker-metadata-action" {} with docker/bake-action@v4. When using 5.4.0, I was able to override the tags defined in my docker-bake.hcl file with the outputs of the docker/metadata-action, but now the tags no longer get overwritten with 5.5.0.

### Expected behaviour

I would expect that if I have the following in my docker-bake.hcl file, the output of docker/metadata-action@v5.5.0 would override the tags defined in the targets. 
``
target "docker-metadata-action" {}

target "_common" {
  inherits = ["docker-metadata-action"]
}

target "example1" {
  inherits = ["_common"]
  tags = ["example1:latest"]
}
``

### Actual behaviour

The outputs from docker/metadata-action@v5.5.0 do not override the tags defined in my docker-bake.hcl. When using v5.4.0 of docker/metadata-action, the tags were successfully overwritten.

### YAML workflow

```yaml
- name: Extract Docker metadata for data_manager
        id: meta
        uses: docker/metadata-action@v5.5.0
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}_${{ matrix.target }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
          bake-target: ${{ matrix.target }}
      - name: Build and push
        uses: docker/bake-action@v4
        with:
          targets: ${{ matrix.target }}
          files: |
            ${{ steps.meta.outputs.bake-file }}
            ./docker-bake.hcl
          push: true
          set: |
            *.cache-from=type=gha,scope=${{ matrix.target }}
            *.cache-to=type=gha,scope=${{ matrix.target }},mode=max
```
