### ISSUE TITLE
Generating tags for multiple bake targets

### ISSUE THREAD

**Issue by Pesa** [docker/metadata-action#398]
### Description

Let's say I have the following `docker-bake.hcl`:

```hcl
group "default" {
  targets = ["foo", "bar"]
}

target "foo" {
  dockerfile = "Dockerfile.foo"
  tags = ["my/foo:latest"]
}

target "bar" {
  dockerfile = "Dockerfile.bar"
  tags = ["my/bar:latest"]
}
```

The tags listed above function a bit like defaults, i.e., they're used when I run bake locally for testing. On GitHub Actions, however, I'd like to use `docker/metadata-action` to generate a list of tags based on various criteria (semver, date, etc...). These generated tags should replace the `:latest` tag from `docker-bake.hcl`, but I still want to keep the base name of the two images (`my/foo` and `my/bar`).

This would be trivial to accomplish with a single target (using the `images` input), but I didn't find a way to do it for multiple targets, where each target has a distinct image name.

Apologies if I missed something obvious (seems odd that this use case isn't already supported, since the whole point of bake is orchestrating the build of multiple targets).

**Comment by crazy-max** [comment]
You can use the [matrix feature](https://docs.docker.com/build/bake/reference/#targetmatrix) for this purpose, like:

```hcl
target "default" {
  name = "build-${tgt}"
  matrix = {
    tgt = ["foo", "bar"]
  }
  dockerfile = "Dockerfile.${tgt}"
  tags = ["my/${tgt}:latest"]
}
```

**Comment by Pesa** [comment]
@crazy-max sorry, I'm not sure I understand. How would I combine the matrix with the tags generated by `docker/metadata-action`? If I set:

```
inherits = ["docker-metadata-action"]
```

isn't that going to overwrite the whole tag `my/${tgt}:latest`?

**Comment by Pesa** [comment]
Basically, I would need something like this:

```hcl
// docker-bake.hcl

target "foo" {
  name = "foo-${version}"
  matrix = {
    version = [...list of version tags generated by metadata-action...] // ???
  }
  dockerfile = "Dockerfile.foo"
  tags = ["my/foo:${version}"]
}
```

And then I would call `metadata-action` with an empty `images` input so that it generates raw version tags without base name.

**Comment by int128** [comment]
I could generate the tags for each target using [for expression](https://developer.hashicorp.com/terraform/language/expressions/for). Here is an example.

```hcl
variable "TAG_BASE" {}

target "docker-metadata-action" {}

target "service1" {
  inherits = ["docker-metadata-action"]
  context = "."
  dockerfile = "service1.dockerfile"
  tags = [for tag in target.docker-metadata-action.tags : "${TAG_BASE}/service1:${tag}"]
}

target "service2" {
  inherits = ["docker-metadata-action"]
  context = "."
  dockerfile = "service2.dockerfile"
  tags = [for tag in target.docker-metadata-action.tags : "${TAG_BASE}/service2:${tag}"]
}
```

```yaml
      - uses: docker/metadata-action@v5
        id: metadata
      - uses: docker/bake-action@v5
        env:
          TAG_BASE: my/foo # something like ghcr.io/${{ github.repository }}
        with:
          push: true
          files: |
            ./docker-bake.hcl
            ${{ steps.metadata.outputs.bake-file }}
```

It will build the image tags of `my/foo/service1:latest` and `my/foo/service2:latest`.
