### ISSUE TITLE
`SOURCE_DATE_EPOCH` is not respected

### ISSUE THREAD

**Issue by Pesa** [docker/metadata-action#403]
### Description

`metadata-action` does not seem to honor the `SOURCE_DATE_EPOCH` [env variable](https://reproducible-builds.org/docs/source-date-epoch/) when generating labels and annotations such as `org.opencontainers.image.created`. I know these can be overridden by the calling workflow, but it would be nice if the action supported `SOURCE_DATE_EPOCH` by default, for a better out-of-the-box experience.

I'm not sure if `SOURCE_DATE_EPOCH` should also affect tags that use the `{{date}}` expression. Personally I don't think it should. Maybe a new expression `{{source_date_epoch}}` can be added that takes the timestamp from the env variable and formats it as specified, instead of using the current time, but this can be considered separately later.

**Comment by crazy-max** [comment]
Sounds good thanks

**Comment by lvjp** [comment]
I think that this is related to the code in [src/meta.ts](https://github.com/docker/metadata-action/blob/70b2cdc6480c1a8b86edf1777157f8f437de2166/src/meta.ts#L41) :
```typescript
this.date = new Date();
```

For now, I have a little workaround :
```yaml
- id: git-timestamp
  run: echo "iso8601=$(git log -n1 --pretty=%cI)" >> "${GITHUB_OUTPUT}"

- uses: docker/metadata-action@v5.5.1
  id: meta
  with:
    labels: "org.opencontainers.image.created=${{ steps.git-timestamp.outputs.iso8601 }}"
```
