### ISSUE TITLE
refs with uppercase characters trigger an error in buildx (branch names with uppercase characters)

### ISSUE THREAD

**Issue by WarpedPixel** [docker/metadata-action#405]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/metadata-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

I have a mixed case user name. This means that a branch might be called `WarpedPixel/issue200`, which generates a ref `WarpedPixel-issue200`. This triggers an error in buildx:
```
ERROR: invalid tag "WarpedPixel-issue455": repository name must be lowercase
```

### Expected behaviour

metadata action should generate sanitized, valid tags only. In this situation it should convert the username to lower case.

### Actual behaviour

Throws an error. I can't really use branch names with mixed case (which are created automatically by other tools like vscode). For such branches, I don't know what the workaround that would allow me to use the metadata action in a GitHub Actions build.

### YAML workflow

```yaml
- name: Docker metadata
          id: meta
          uses: docker/metadata-action@v5
          with:
            tags: |
              type=ref,event=branch
              type=ref,event=pr
              type=semver,pattern={{version}},enable={{is_default_branch}}
              type=sha
              type=sha,format=long

          - name: Build Frontend
            id: build_frontend
            uses: docker/build-push-action@v5.3.0
            with:
              context: ./frontend
              build-args: VERSION=${{ needs.versioning.outputs.version }}
              push: false
              cache-from: type=gha
              cache-to: type=gha,mode=max
              target: production
              outputs: type=image
              tags: |
                ${{ needs.versioning.outputs.tags }}
                frontend:production
              labels: ${{ needs.versioning.outputs.labels }}
```
