### ISSUE TITLE
Commit SHA in pull request event is incorrect.

### ISSUE THREAD

**Issue by iwata** [docker/metadata-action#414]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/metadata-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

I'm using `type=ref,event=pr,suffix=-{{sha}}` as `tags` option. But `sha` is incorrect.

### Expected behaviour

`sha` returns `github.event.pull_request.head.sha`.

### Actual behaviour

`sha` returns `github.sha`.

### YAML workflow

```yaml
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: app
          tags: |
            type=ref,event=pr,suffix=-{{sha}}
      - name: debug
        run: |
          echo ${{ steps.meta.outputs.tags }}
          git rev-parse --short ${{ github.event.pull_request.head.sha }}
          git rev-parse --short "$GITHUB_SHA"
```

### Workflow logs
```
pr-xxxx-937f26e
f03bb03
937f26e
```
