### ISSUE TITLE
Increasing short commit hash length is a breaking change

### ISSUE THREAD

**Issue by RobinDaugherty** [docker/metadata-action#479]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/metadata-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

https://github.com/docker/metadata-action/pull/467 increased the default length of the commit hash created by the `sha` directive

This was released in [v5.6.0](https://github.com/docker/metadata-action/releases/tag/v5.6.0) which made it immediately apply to everyone whose workflow specified release `v5` in their actions.

This change unfortunately broke my workflows, because other parts of our workflows were hard-coded to match the size of the tags created by this action.

Please consider pulling this release and re-releasing it as v6.

### Expected behaviour

v5 creates short "sha" tags with 7-character commit hash

### Actual behaviour

v5 suddenly creates short "sha" tags with 12-character commit hash

### YAML workflow

```yaml
- name: Docker image metadata
  id: metadata
  uses: docker/metadata-action@v5
  with:
    images: |
      ${{ steps.ghcr_image_name.outputs.name }}
    tags: |
      type=ref,event=branch
      type=ref,event=pr
      type=semver,pattern={{major}}.{{minor}}.{{patch}}
      type=sha

- name: Get deployment tag
  id: get_deployment_tag
  # The following variables are made available to subsequent jobs to be used to find the specific Docker image that was built and pushed by this job.
  run: |
    echo "deployment_tag=sha-$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
    echo "build_image=${{ steps.ghcr_image_name.outputs.name }}:sha-$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
```

### BuildKit logs

```text

```
