### ISSUE TITLE
Expose pull request head ref as `{{branch}}` variable

### ISSUE THREAD

**Issue by fabn** [docker/metadata-action#485]
### Description

When using [`{{branch}}`](https://github.com/marketplace/actions/docker-metadata-action?version=v5.6.1#branch) variable in a `pull_request` event the output is '' (as documented).

It would be super useful to have it populated with `github.event.pull_request.head.ref` to compose tags like the following:

```yaml
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          tags: |
            type=sha,format=short,prefix={{branch}}-
```

At the moment I'm doing something like:

```yml
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          tags: |
            type=sha,format=short,prefix=${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || '{{branch}}' }}-
```

But it seems a hack to me, is there any drawback in doing that?
