### ISSUE TITLE
Add option to disable built-in all labels

### ISSUE THREAD

**Issue by Sytten** [docker/metadata-action#486]
### Description

Hi!
I think it would be good to add an option to disable the built-in labels and give the user more control over it, not just a field with extra labels.
The filtering seems also broken as I can see some labels with empty string in the output of the step even though the code tries to filter that out.
Thanks

**Comment by crazy-max** [comment]
> Add option to disable built-in all labels

What would be the point then? If you don't want to use them, then just omit setting them in underlying steps?

Can you give more details with your workflow / use case? I might miss something.

**Comment by Sytten** [comment]
I guess that is a fair point, it was mostly to be able to reuse it (but I refactored to use TARGETARCH):
```
      - name: Generate Docker metadata (slim)
        id: meta-slim
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/caido/caido
            caido/caido
          flavor: |
            latest=true
            suffix=-slim,onlatest=true
          tags: |
            type=raw,value=${{ needs.meta.outputs.version }}
            type=semver,pattern={{version}},value=${{ needs.meta.outputs.version }}

      - name: Build and push x86_64 (slim)
        if: inputs.dry-run == false
        uses: docker/build-push-action@v5
        with:
          context: docker/x86_64
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta-slim.outputs.tags }}
          file: docker/Dockerfile.slim

      - name: Build and push aarch64 (slim)
        if: inputs.dry-run == false
        uses: docker/build-push-action@v5
        with:
          context: docker/aarch64
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta-slim.outputs.tags }}
          file: docker/Dockerfile.slim
```
Could also help for https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners
