### ISSUE TITLE
Take leverage of variables into labels

### ISSUE THREAD

**Issue by lvjp** [docker/metadata-action#488]
### Description

To help the resolution of #403, when `SOURCE_DATE_EPOCH` is the commit date, since #471, we can now use the variable `commit_date` but it does not interpolate within the labels.

With this input :

```yaml
      - uses: docker/metadata-action@v5.6.1
        with:
          labels: |
            org.opencontainers.image.created={{commit_date YYYY-MM-DDTHH:mm:ssZ}}
```

My test :

```diff
--- expected
+++actual
-org.opencontainers.image.created=2024-12-06T04:45:03+01:00
+org.opencontainers.image.newcreated={{commit_date 'YYYY-MM-DDTHH:mm:ssZ'}}
```
