### ISSUE TITLE
"prefix" field introduces extra hyphen at beginning and end of tag

### ISSUE THREAD

**Issue by calumblair** [docker/metadata-action#513]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/metadata-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

The `prefix` tag is introducing an extra hyphen at the beginning and end of the generated tag. This makes the tag start with a hypen, which makes the tag invalid, and causes docker image tagging to fail.

### Expected behaviour

when I use `prefix` to modify a tag, I get exactly what's in the `prefix` field. If I have an image with tag `0.1.2` and specify a prefix of `prod-`, I'd expect to get a tag `prod-0.1.2`

### Actual behaviour

when I use `prefix` to modify a tag, if I have an image with tag `0.1.2` and specify a prefix of `prod-`, I see a tag `-prod--0.1.2` which Docker treats as invalid as it starts with a `-`.

### Repository URL

https://github.com/calumblair/docker-meta-test

### Workflow run URL

https://github.com/calumblair/docker-meta-test/actions/runs/13921165249

### YAML workflow

```yaml
name: meta test

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: name/app
          tags: |
            type=ref,event=branch
            type=raw,priority=100,value=0.1.2,prefix='prod-'
```

### Workflow logs
Extract:
```
Processing tags input
  type=ref,event=branch,enable=true,priority=600
  type=raw,priority=100,value=0.1.2,prefix='prod-',enable=true
Processing flavor input
Docker image version
Docker tags
  name/app:main
  name/app:-prod--0.1.2
```
Full log here: [action-job-logs.txt](https://github.com/user-attachments/files/19316731/action-job-logs.txt)

### BuildKit logs

```text

```

**Comment by calumblair** [comment]
```
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: name/app
          tags: |
            type=ref,event=branch
            type=raw,priority=100,value=0.1.2,prefix=prod-
```
No, removing quotes fixes the problem:
```
Processing tags input
  type=ref,event=branch,enable=true,priority=600
  type=raw,priority=100,value=0.1.2,prefix=prod-,enable=true
Processing flavor input
Docker image version
Docker tags
  name/app:main
  name/app:prod-0.1.2
```
Thanks for your help, removing quotes has solved my problem.  Closing.
