### ISSUE TITLE
Monorepo usage?

### ISSUE THREAD

**Issue by nwmcsween** [docker/metadata-action#86]
Would it be possible to use this with a monorepo of docker images? If so how?

**Comment by crazy-max** [comment]
@nwmcsween Do you have a lin kto your repo and/or workflow with your use case please?

**Comment by nwmcsween** [comment]
I'll explain what I was hoping to do (although others may have differing
opinions) is to use nested tags "package/version" as releases and for
building ./package/$version.dockerfile or ./package/Dockerfile within the
repo. If this isn't ideal then I would be ok with other ideas

**Comment by JasonGiedymin** [comment]
I believe all you need to do is add to the naming. I do this now. Typically most of the examples and code you see only show `ghcr.io/OWNER/PROJECT`. However `ghcr.io/OWNER/PROJECT/your-custom-image` will work just fine.

You'll just have to make sure that for the `docker/build-push-action` you set the correct file and context path if they're not at the root of the repo.

**Comment by crazy-max** [comment]
@nwmcsween By using a matrix strategy for example:

```yaml
name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context:
          - subfolder1
          - subfolder2
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
     -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: name/app
          flavor: |
            prefix=${{ matrix.context }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```
