### ISSUE TITLE
Double quotes in repository description causes downstream build-push-action error

### ISSUE THREAD

**Issue by patrickkwang** [docker/metadata-action#87]
#### Steps to reproduce this issue

* In the repository description, use some double quotes.
* Run docker/metadata-action@v3
* ...followed by docker/build-push-action@v2 with `labels: ${{ steps.meta.outputs.labels }}`

#### Expected behaviour

I hoped that this would run without errors and push a docker image.

#### Actual behaviour

docker/build-push-action fails with
`Error: Invalid Opening Quote: a quote is found inside a field at line 2`

### Configuration

* Repository URL (if public): <https://github.com/TranslatorSRI/filter_results_top_n/> - Note that I have since converted to single quotes in the description, which resolves the issue.
* Build URL (if public): <https://github.com/TranslatorSRI/filter_results_top_n/runs/2584098697?check_suite_focus=true>

```yml
name: 'release'

on:
    release:
        types: [published]

jobs:
    push_to_registry:
        name: Push Docker image to GitHub Packages tagged with "latest" and version number.
        runs-on: ubuntu-latest
        permissions: 
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v3
              with:
                # list of Docker images to use as base name for tags
                images: |
                  ghcr.io/TranslatorSRI/filter_results_top_n
                # add latest tag when appropriate
                flavor: |
                  latest=auto
                # generate Docker tags based on the following events/attributes
                tags: |
                  type=semver,pattern={{version}}
                  type=semver,pattern={{major}}.{{minor}}
                  type=semver,pattern={{major}}
                  type=sha

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to GHCR
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
```

### Logs

[logs_7.zip](https://github.com/docker/metadata-action/files/6501848/logs_7.zip)

### Notes

A workaround is simply to avoid double quotes in the repository description.

A potential solution is to escape the quotes in the labels by doubling them: https://github.com/docker/build-push-action/issues/245#issuecomment-738261796, but this may not be kind to other uses of the metadata output.
