### ISSUE TITLE
Question: list vs YAML array for inputs 

### ISSUE THREAD

**Issue by tpolekhin** [docker/metadata-action#88]
Hello!
I was wondering why use multi-line string `list` instead of YAML array for inputs?
Maybe it's a technical limitation and it's okay if so I just wanted to check.

I'm trying to pass build args to the docker build with meta information and having difficulties because of this `list` type.
https://github.com/docker/metadata-action provides an easy way to inject meta labels for the container,
exporting a `list` of OCI labels that you can then use for `labels:` input. I guess they used a `list` type for their output to match this action input type.

I'm trying to reuse some of them as build args to also inject this information into the app binary, but it doesn't work because `steps.meta.outputs.labels` is not an array. I was looking around for a conversion function or tool that would help me to get this values out of `labels`, but couldn't find anything.
```
      - name: Prepare image metadata
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: repo/app

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILDTIME=${{ steps.meta.outputs.labels['org.opencontainers.image.created'] }}
            VERSION=${{ steps.meta.outputs.labels['org.opencontainers.image.version'] }}
            REVISION=${{ steps.meta.outputs.labels['org.opencontainers.image.revision'] }}
```

I think it would be more convenient to work with JSON/YAML Arrays, just because there's a lot more supported tooling and operations than for just a list of strings.

Curious to get your opinion on this
