### ISSUE TITLE
Flavor suffix does not append to latest tag

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [docker/metadata-action#95]
### Behaviour

When using a flavor suffix, it will not be appended to the latest tag

#### Steps to reproduce this issue

1. Set up metadata-action to use any flavor suffix
2. Push a tag to trigger the latest tag release
3. Watch as the suffix is not appended to the latest tag

#### Expected behaviour

Flavor suffix should be appended to the suffix

#### Actual behaviour

Creates the latest tag without the suffix

### Configuration

* Repository URL: https://github.com/Cyb3r-Jak3/pypy-flask
* Build URL: https://github.com/Cyb3r-Jak3/pypy-flask/runs/2652730017?check_suite_focus=true

```yml
# ommited irreverent steps
jobs:
  Slim:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: cyb3rjak3/pypy-flask,ghcr.io/cyb3r-jak3/pypy-flask,registry.gitlab.com/cyb3r-jak3/pypy-flask
        tags: |
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
        labels: |
          org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/pypy-flask.git
          org.label-schema.schema-version=1.0.0-rc1

    - name: Slim Build and Push
      uses: docker/build-push-action@v2.4.0
      with:
        platforms: linux/amd64,linux/arm64
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        push: ${{ startsWith(github.ref, 'refs/tags/v') }}
        file: Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  Alpine:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: cyb3rjak3/pypy-flask,ghcr.io/cyb3r-jak3/pypy-flask,registry.gitlab.com/cyb3r-jak3/pypy-flask
        flavor: |
          suffix=-alpine
        tags: |
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
        labels: |
          org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/pypy-flask.git
          org.label-schema.schema-version=1.0.0-rc1

    - name: Alpine Build and Push
      uses: docker/build-push-action@v2.4.0
      with:
        platforms: linux/amd64,linux/arm64
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        push: ${{ startsWith(github.ref, 'refs/tags/v') }}
        file: alpine.Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
```

### Logs

[Raw Logs](https://pipelines.actions.githubusercontent.com/F4K5Ou1vq0DL9BN8Oil75dpS8ioyG95KqkEfaEfGHipKzyVg8j/_apis/pipelines/1/runs/31/signedlogcontent/4?urlExpires=2021-05-25T13%3A48%3A27.3464559Z&urlSigningMethod=HMACV1&urlSignature=UfOz%2Fz2bSgg9Cky1dXasvyW2Om9S3cM3FMYXxvG8UfA%3D)
[Logs Archive](https://github.com/docker/metadata-action/files/6539767/logs_31.zip)
